### ISSUE TITLE
Missing metabolite metadata

### ISSUE THREAD

**Issue by shackett** [KevinGHicks/MIDAS#2]
@KevinGHicks I can't match the metabolite headers of MIDAS_input_dataset.txt to the metabolite annotations you have provided me. I fixed most of the mis-matched names but some I can't address.

I moved and updated a version of the metadata to inst/extdata/MIDAS_metabolites.txt

I tried to join these names in R/data.R. You can use this function (prepare_metabolites()) to see the conflicts. Please either replace the metadata file with an up to date on or resolve the conflicts in the existing metadata.

**Comment by KevinGHicks** [comment]
@shackett I ran the prepare_metabolites function in R/data.R with no errors, but it did not generate a list or dataframe to view. "view(prepare_metabolites)" does nothing. What am I missing to view the conflicts?

Alternatively, I can compare the metabolite annotations between MIDAS_input_dataset.txt and MIDAS_metabolites.txt to see if any names are off?
